# Generated by Django 2.2 on 2020-08-29 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnData',
            new_name='RegionsData',
        ),
        migrations.AlterModelTable(
            name='aseancountry',
            table='asean_country',
        ),
        migrations.AlterModelTable(
            name='regionsdata',
            table='regions_data',
        ),
        migrations.AlterModelTable(
            name='saarccountry',
            table='saarc_country',
        ),
    ]
