# Generated by Django 2.2 on 2020-08-29 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0002_auto_20200829_1930'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aseancountry',
            table='un_asean_country',
        ),
        migrations.AlterModelTable(
            name='regionsdata',
            table='un_regions_data',
        ),
        migrations.AlterModelTable(
            name='saarccountry',
            table='un_saarc_country',
        ),
    ]
