# Generated by Django 2.2 on 2020-08-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0004_auto_20200829_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aseancountry',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='regiondata',
            name='region',
            field=models.CharField(max_length=40),
        ),
    ]
