# Generated by Django 2.2 on 2020-08-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0006_auto_20200829_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiondata',
            name='region',
            field=models.CharField(max_length=100),
        ),
    ]
