# Generated by Django 2.2 on 2020-08-29 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0007_auto_20200829_2103'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aseancountry',
            table='asean_countries',
        ),
        migrations.AlterModelTable(
            name='bricscountry',
            table='brics_countries',
        ),
        migrations.AlterModelTable(
            name='g4country',
            table='g4_countries',
        ),
        migrations.AlterModelTable(
            name='g7country',
            table='g7_countries',
        ),
        migrations.AlterModelTable(
            name='saarccountry',
            table='saarc_countries',
        ),
    ]
