# Generated by Django 2.2 on 2020-08-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0008_auto_20200829_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aseancountry',
            name='short_name',
        ),
    ]
